/* Golden Pride Hub v5 — Admin Control Center */
const MAX_IMAGE_BYTES = 700 * 1024;

document.addEventListener("DOMContentLoaded",()=>{
  if(!document.body.classList.contains("admin-page"))return;
  initAdminTabs(); loadAdminStats(); bindBroadcast(); bindAnnouncementForm(); bindEventForm(); bindGalleryForm(); bindAchievementForm(); bindImagePreviews();
  loadAdminBroadcasts(); loadAdminAnnouncementsTable(); loadAdminUsersTable(); loadAdminEventsTable(); loadAdminGalleryTable(); loadAdminAchievementsTable();
  const s=document.getElementById("admin-member-search"); if(s)s.addEventListener("input",debounce(()=>loadAdminUsersTable(s.value),250));
  const msg=document.getElementById("broadcast-message"),count=document.getElementById("broadcast-count"); if(msg)msg.addEventListener("input",()=>count.textContent=`${msg.value.length} / 220`);
  ["broadcast-name","broadcast-message"].forEach(id=>document.getElementById(id)?.addEventListener("input",updateBroadcastPreview));
});
function initAdminTabs(){document.querySelectorAll(".admin-tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-panel").forEach(x=>x.classList.remove("active"));tab.classList.add("active");document.getElementById(tab.dataset.target)?.classList.add("active");history.replaceState(null,"",`#${tab.dataset.target.replace("tab-","")}`)}));const h=location.hash.replace("#","");if(h){const t=document.querySelector(`.admin-tab[data-target="tab-${h}"]`);t?.click();}}
async function readImage(input){const f=input?.files?.[0];if(!f)return null;if(f.size>MAX_IMAGE_BYTES)throw new Error("Image too large. Please choose a photo under 700KB.");return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Failed to read image."));r.readAsDataURL(f);});}
function bindImagePreviews(){[["gallery-image","gallery-image-preview"],["announcement-image","announcement-image-preview"],["achievement-image","achievement-image-preview"]].forEach(([a,b])=>{const i=document.getElementById(a),p=document.getElementById(b);i?.addEventListener("change",()=>{const f=i.files?.[0];if(!f){p.style.display="none";return}const r=new FileReader();r.onload=()=>{p.src=r.result;p.style.display="block"};r.readAsDataURL(f);});});}
async function count(c){try{return (await db.collection(c).get()).size}catch{return 0}}
async function loadAdminStats(){const [u,a,e,g,t]=await Promise.all([count(COLLECTIONS.USERS),count(COLLECTIONS.ANNOUNCEMENTS),count(COLLECTIONS.EVENTS),count(COLLECTIONS.GALLERY),count(COLLECTIONS.ACHIEVEMENTS)]);setText("admin-stat-users",u);setText("admin-stat-announcements",a);setText("admin-stat-events",e);setText("admin-stat-gallery",g);setText("admin-stat-achievements",t)}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function updateBroadcastPreview(){setText("broadcast-preview-name",document.getElementById("broadcast-name")?.value.trim()||"Admin Name");setText("broadcast-preview-message",document.getElementById("broadcast-message")?.value.trim()||"Your message will appear here.")}
async function bindBroadcast(){const f=document.getElementById("broadcast-form");if(!f)return;const name=document.getElementById("broadcast-name");try{auth.onAuthStateChanged(async u=>{if(u&&name&&!name.value){const s=await db.collection(COLLECTIONS.USERS).doc(u.uid).get();name.value=s.data()?.fullname||u.displayName||"Admin";updateBroadcastPreview();}})}catch{}
f.addEventListener("submit",async e=>{e.preventDefault();const u=auth.currentUser,n=name.value.trim(),m=document.getElementById("broadcast-message").value.trim(),duration=Number(document.getElementById("broadcast-duration").value);if(!u||!n||!m)return showToast("Your admin name or custom message is missing.","warning");const btn=f.querySelector("button[type=submit]");btn.disabled=true;try{await db.collection("broadcasts").add({sender:n,message:m,uid:u.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp(),active:true,expiresAt:new Date(Date.now()+duration+5000),duration});showToast("Live message sent to members.","success");f.reset();name.value=n;updateBroadcastPreview();loadAdminBroadcasts()}catch(err){showToast(err.message||"Broadcast failed. Check Firestore rules.","error")}finally{btn.disabled=false}})}
async function loadAdminBroadcasts(){const t=document.getElementById("admin-broadcasts-table");if(!t)return;try{const s=await db.collection("broadcasts").orderBy("createdAt","desc").limit(20).get();t.innerHTML=s.docs.map(d=>{const x=d.data(),active=x.active!==false&&(!x.expiresAt||getDateValue(x.expiresAt)?.getTime()>Date.now());return `<tr><td>${sanitize(x.sender||"Admin")} <span title="Verified admin">✅</span></td><td>${sanitize(x.message||"")}</td><td>${formatDate(x.createdAt)||"Just now"}</td><td><span class="status-pill ${active?"status-live":"status-muted"}">${active?"LIVE":"ENDED"}</span></td><td><button class="btn-icon" onclick="deleteBroadcast('${d.id}')" title="Delete"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join("")||`<tr><td colspan="5" class="empty-state">No broadcasts yet.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="5" class="empty-state">Broadcast history unavailable. Add the broadcasts collection to your Firestore rules.</td></tr>`}}
async function deleteBroadcast(id){if(!await confirmDialog("Delete this broadcast?"))return;try{await db.collection("broadcasts").doc(id).delete();showToast("Broadcast deleted.","success");loadAdminBroadcasts()}catch{showToast("Unable to delete broadcast.","error")}}
function bindAnnouncementForm(){const f=document.getElementById("announcement-form");if(!f)return;f.addEventListener("submit",async e=>{e.preventDefault();const id=document.getElementById("announcement-id").value,title=document.getElementById("announcement-title").value.trim(),content=document.getElementById("announcement-content").value.trim(),pinned=document.getElementById("announcement-pinned").checked,btn=f.querySelector("button[type=submit]");if(!title||!content)return showToast("Title and content are required.","warning");btn.disabled=true;try{const image=await readImage(document.getElementById("announcement-image")),payload={title,content,pinned,author:currentUserData?.fullname||auth.currentUser?.displayName||"Admin"};if(image)payload.image=image;if(id)await db.collection(COLLECTIONS.ANNOUNCEMENTS).doc(id).update(payload);else{payload.createdAt=firebase.firestore.FieldValue.serverTimestamp();await db.collection(COLLECTIONS.ANNOUNCEMENTS).add(payload)}showToast(id?"Announcement updated.":"Announcement published.","success");f.reset();document.getElementById("announcement-id").value="";document.getElementById("announcement-image-preview").style.display="none";loadAdminAnnouncementsTable();loadAdminStats()}catch(err){showToast(err.message||"Failed to save announcement.","error")}finally{btn.disabled=false}})}
async function loadAdminAnnouncementsTable(){const t=document.getElementById("admin-announcements-table");if(!t)return;try{const s=await db.collection(COLLECTIONS.ANNOUNCEMENTS).orderBy("createdAt","desc").get();t.innerHTML=s.docs.map(d=>{const x=d.data();return `<tr><td>${sanitize(x.title)}</td><td>${sanitize(x.author)}</td><td>${formatDate(x.createdAt)}</td><td>${x.pinned?"📌":"—"}</td><td class="table-actions"><button class="btn-icon" onclick="editAnnouncement('${d.id}')"><i class="fa-solid fa-pen"></i></button><button class="btn-icon" onclick="deleteAnnouncement('${d.id}')"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join("")||`<tr><td colspan="5" class="empty-state">No announcements yet.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="5" class="empty-state">Unable to load announcements.</td></tr>`}}
async function editAnnouncement(id){const s=await db.collection(COLLECTIONS.ANNOUNCEMENTS).doc(id).get(),d=s.data()||{};document.getElementById("announcement-id").value=id;document.getElementById("announcement-title").value=d.title||"";document.getElementById("announcement-content").value=d.content||"";document.getElementById("announcement-pinned").checked=!!d.pinned;const p=document.getElementById("announcement-image-preview");if(d.image){p.src=d.image;p.style.display="block"}document.querySelector('[data-target="tab-announcements"]')?.click();document.getElementById("announcement-form").scrollIntoView({behavior:"smooth"})}
async function deleteAnnouncement(id){if(!await confirmDialog("Delete this announcement?"))return;try{await db.collection(COLLECTIONS.ANNOUNCEMENTS).doc(id).delete();showToast("Announcement deleted.","success");loadAdminAnnouncementsTable();loadAdminStats()}catch{showToast("Delete failed.","error")}}
function bindEventForm(){const f=document.getElementById("event-form");if(!f)return;f.addEventListener("submit",async e=>{e.preventDefault();const title=document.getElementById("event-title").value.trim(),description=document.getElementById("event-description").value.trim(),location=document.getElementById("event-location").value.trim(),date=document.getElementById("event-date").value;if(!title||!date)return showToast("Title and date are required.","warning");try{await db.collection(COLLECTIONS.EVENTS).add({title,description,location,date:new Date(date),createdAt:firebase.firestore.FieldValue.serverTimestamp()});showToast("Event added.","success");f.reset();loadAdminEventsTable();loadAdminStats()}catch{showToast("Failed to add event.","error")}})}
async function loadAdminEventsTable(){const t=document.getElementById("admin-events-table");if(!t)return;try{const s=await db.collection(COLLECTIONS.EVENTS).orderBy("date","desc").get();t.innerHTML=s.docs.map(d=>{const x=d.data();return `<tr><td>${sanitize(x.title)}</td><td>${sanitize(x.location)}</td><td>${formatDate(x.date)}</td><td><button class="btn-icon" onclick="viewRsvps('${d.id}','${sanitize(x.title).replace(/'/g,"&#39;")}')"><i class="fa-solid fa-user-group"></i></button><button class="btn-icon" onclick="deleteEvent('${d.id}')"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join("")||`<tr><td colspan="4" class="empty-state">No events yet.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="4" class="empty-state">Unable to load events.</td></tr>`}}
async function deleteEvent(id){if(!await confirmDialog("Delete this event?"))return;try{await db.collection(COLLECTIONS.EVENTS).doc(id).delete();showToast("Event deleted.","success");loadAdminEventsTable();loadAdminStats()}catch{showToast("Delete failed.","error")}}
async function viewRsvps(id,title){try{const s=await db.collection(COLLECTIONS.EVENTS).doc(id).collection("rsvps").orderBy("timestamp").get();const o=document.createElement("div");o.className="confirm-overlay show";o.innerHTML=`<div class="confirm-box glass" style="max-width:430px;text-align:left"><h3>Attendees — ${sanitize(title)}</h3><div style="max-height:300px;overflow:auto;margin:15px 0">${s.empty?'<p class="empty-state">No RSVPs yet.</p>':s.docs.map((x,i)=>`<p>${i+1}. ${sanitize(x.data().fullname||"Member")}</p>`).join("")}</div><div class="confirm-actions"><button class="btn btn-primary" id="close-rsvps">Close</button></div></div>`;document.body.appendChild(o);o.querySelector("#close-rsvps").onclick=()=>o.remove()}catch{showToast("Unable to load RSVPs.","error")}}
async function loadAdminUsersTable(term=""){const t=document.getElementById("admin-users-table");if(!t)return;try{const s=await db.collection(COLLECTIONS.USERS).orderBy("fullname").get(),q=term.trim().toLowerCase();const docs=s.docs.filter(d=>(`${d.data().fullname||""} ${d.data().email||""}`).toLowerCase().includes(q));t.innerHTML=docs.map(d=>{const x=d.data();return `<tr><td>${sanitize(x.fullname)}</td><td>${sanitize(x.email)}</td><td><span class="role-badge ${x.role===ROLES.ADMIN?"badge-admin":"badge-member"}">${sanitize(x.role||"member")}</span></td><td><button class="btn-icon" onclick="toggleUserRole('${d.id}','${sanitize(x.role||ROLES.MEMBER)}')"><i class="fa-solid fa-user-gear"></i></button></td></tr>`}).join("")||`<tr><td colspan="4" class="empty-state">No members found.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="4" class="empty-state">Unable to load members.</td></tr>`}}
async function toggleUserRole(uid,role){const nr=role===ROLES.ADMIN?ROLES.MEMBER:ROLES.ADMIN;if(!await confirmDialog(`Change this user's role to ${nr}?`))return;try{await db.collection(COLLECTIONS.USERS).doc(uid).update({role:nr});showToast("User role updated.","success");loadAdminUsersTable()}catch{showToast("Unable to update role.","error")}}
function bindGalleryForm(){const f=document.getElementById("gallery-form");if(!f)return;f.addEventListener("submit",async e=>{e.preventDefault();try{const image=await readImage(document.getElementById("gallery-image"));if(!image)throw new Error("Choose a photo first.");await db.collection(COLLECTIONS.GALLERY).add({image,caption:document.getElementById("gallery-caption").value.trim(),createdAt:firebase.firestore.FieldValue.serverTimestamp(),author:currentUserData?.fullname||"Admin"});showToast("Photo uploaded.","success");f.reset();document.getElementById("gallery-image-preview").style.display="none";loadAdminGalleryTable();loadAdminStats()}catch(err){showToast(err.message||"Upload failed.","error")}})}
async function loadAdminGalleryTable(){const t=document.getElementById("admin-gallery-table");if(!t)return;try{const s=await db.collection(COLLECTIONS.GALLERY).orderBy("createdAt","desc").get();t.innerHTML=s.docs.map(d=>{const x=d.data();return `<tr><td><img src="${sanitize(x.image||"")}" style="width:58px;height:42px;object-fit:cover;border-radius:8px" alt=""></td><td>${sanitize(x.caption||"")}</td><td><button class="btn-icon" onclick="deleteGallery('${d.id}')"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join("")||`<tr><td colspan="3" class="empty-state">No gallery items yet.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="3" class="empty-state">Unable to load gallery.</td></tr>`}}
async function deleteGallery(id){if(!await confirmDialog("Delete this photo?"))return;try{await db.collection(COLLECTIONS.GALLERY).doc(id).delete();showToast("Photo deleted.","success");loadAdminGalleryTable();loadAdminStats()}catch{showToast("Delete failed.","error")}}
function bindAchievementForm(){const f=document.getElementById("achievement-form");if(!f)return;f.addEventListener("submit",async e=>{e.preventDefault();try{const image=await readImage(document.getElementById("achievement-image"));const p={title:document.getElementById("achievement-title").value.trim(),description:document.getElementById("achievement-description").value.trim(),createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(image)p.image=image;await db.collection(COLLECTIONS.ACHIEVEMENTS).add(p);showToast("Achievement added.","success");f.reset();document.getElementById("achievement-image-preview").style.display="none";loadAdminAchievementsTable();loadAdminStats()}catch(err){showToast(err.message||"Failed to add achievement.","error")}})}
async function loadAdminAchievementsTable(){const t=document.getElementById("admin-achievements-table");if(!t)return;try{const s=await db.collection(COLLECTIONS.ACHIEVEMENTS).orderBy("createdAt","desc").get();t.innerHTML=s.docs.map(d=>{const x=d.data();return `<tr><td>${sanitize(x.title)}</td><td>${sanitize((x.description||"").slice(0,90))}</td><td>${formatDate(x.createdAt)}</td><td><button class="btn-icon" onclick="deleteAchievement('${d.id}')"><i class="fa-solid fa-trash"></i></button></td></tr>`}).join("")||`<tr><td colspan="4" class="empty-state">No achievements yet.</td></tr>`}catch{t.innerHTML=`<tr><td colspan="4" class="empty-state">Unable to load achievements.</td></tr>`}}
async function deleteAchievement(id){if(!await confirmDialog("Delete this achievement?"))return;try{await db.collection(COLLECTIONS.ACHIEVEMENTS).doc(id).delete();showToast("Achievement deleted.","success");loadAdminAchievementsTable();loadAdminStats()}catch{showToast("Delete failed.","error")}}
